// Generated by CoffeeScript 2.7.0
(function() {
  /*
    Common Components Renderer
  */
  window.renderHero = function(container, data) {
    var badgeHtml, ctasHtml;
    if (!(container && data)) {
      return;
    }
    badgeHtml = data.badge ? `<div class="badge">
  ${data.badgeIcon || '<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" style="color: #f59e0b"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>'}
  ${data.badge}
</div>` : "";
    ctasHtml = (data.ctas || []).map(function(cta) {
      var targetAttr;
      targetAttr = cta.target ? 'target="_blank" rel="noopener"' : "";
      return `<a href="${cta.link}" class="btn ${cta.class}" ${targetAttr}>${cta.text}</a>`;
    }).join('');
    return container.innerHTML = `<div class="container">
  ${badgeHtml}
  <h1>${data.title}</h1>
  <p>${data.description}</p>
  <div class="hero-ctas" style="${data.ctaStyle || ''}">
    ${ctasHtml}
  </div>
</div>`;
  };

  window.renderFreeResources = function(container, data) {
    var itemsHtml;
    if (!(container && data)) {
      return;
    }
    itemsHtml = (data.items || []).map(function(item) {
      return `<div class="resource-card" style="background: var(--surface); border: 1px solid var(--border-color); border-radius: 12px; padding: 24px; text-align: center;">
  <div style="font-size: 2.5rem; margin-bottom: 12px">${item.icon}</div>
  <h3 style="color: var(--text-main); font-size: 1.1rem; margin-bottom: 8px;">${item.title}</h3>
  <p style="color: var(--text-muted); font-size: 0.95rem">${item.desc}</p>
</div>`;
    }).join('');
    return container.innerHTML = `<div class="container" style="max-width: 900px; margin: auto">
  <div style="text-align: center; margin-bottom: 40px">
    <h2 style="font-size: 2.2rem; color: var(--text-main); margin-bottom: 12px;">
      ${data.title}
    </h2>
    <p style="color: var(--text-muted); font-size: 1.05rem; line-height: 1.6; max-width: 700px; margin: 0 auto 24px;">
      ${data.description}
    </p>
  </div>

  <div class="resources-grid" style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 40px;">
    ${itemsHtml}
  </div>

  <div class="cta-box" style="background: var(--surface-2); border: 2px solid var(--accent); border-radius: 16px; padding: 36px; text-align: center;">
    <h3 style="color: var(--text-main); font-size: 1.5rem; margin-bottom: 12px;">${data.ctaBox.title}</h3>
    <p style="color: var(--text-muted); margin-bottom: 24px">${data.ctaBox.desc}</p>
    <a href="${data.ctaBox.link}" target="_blank" rel="noopener" class="btn btn-primary" style="display: inline-block; font-size: 1.05rem; padding: 14px 36px;">
      ${data.ctaBox.text}
    </a>
  </div>
</div>`;
  };

}).call(this);
