// Generated by CoffeeScript 2.7.0
(function() {
  /*
    Home Page Renderer
  */
  var fetchAndRenderCsvTable, parseCsv, renderCerberus, renderHomeSEO;

  document.addEventListener('DOMContentLoaded', function() {
    var cerberusContainer, heroContainer, resourcesContainer, scheduleContainer, seoContainer;
    heroContainer = document.getElementById('home');
    seoContainer = document.getElementById('seo-root');
    resourcesContainer = document.getElementById('resources-root');
    cerberusContainer = document.getElementById('cerberus-root');
    if (typeof window.HOME_DATA === 'undefined') {
      return;
    }
    // 1. Render Hero
    if (heroContainer && window.HOME_DATA.hero) {
      if (typeof window.renderHero === 'function') {
        window.renderHero(heroContainer, window.HOME_DATA.hero);
      }
    }
    if (seoContainer && window.HOME_DATA.seo) {
      // 2. Render SEO Section
      renderHomeSEO(seoContainer, window.HOME_DATA.seo);
    }
    // 3. Render Free Resources
    if (resourcesContainer && window.HOME_DATA.freeResources) {
      if (typeof window.renderFreeResources === 'function') {
        window.renderFreeResources(resourcesContainer, window.HOME_DATA.freeResources);
      }
    }
    if (cerberusContainer && window.HOME_DATA.cerberus) {
      // 4. Render CERBERUS
      renderCerberus(cerberusContainer, window.HOME_DATA.cerberus);
    }
    // 5. Fetch and Render CSV Table
    scheduleContainer = document.getElementById('csv-table-container');
    if (scheduleContainer) {
      return fetchAndRenderCsvTable("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ7KPcPrcFxZc3TgMAVjH3Zv3FCDdafdD9H8i6IznF0UKUNQ7mak4dyQb1f9jj2jruf1LGryXv3vsyJ/pub?gid=1658759406&single=true&output=csv");
    }
  });

  renderHomeSEO = function(container, data) {
    var ctasHtml;
    ctasHtml = data.ctas.map(function(cta) {
      var iconHtml, targetAttr;
      targetAttr = cta.target ? 'target="_blank" rel="noopener"' : "";
      iconHtml = cta.icon ? `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <line x1="5" y1="12" x2="19" y2="12"></line>
  <polyline points="12 5 19 12 12 19"></polyline>
</svg>` : "";
      return `<a href="${cta.link}" class="btn ${cta.class}" ${targetAttr} style="display: inline-flex; align-items: center; gap: 8px; padding: 12px 24px; font-size: 1.05rem;">
  ${cta.text}
  ${iconHtml}
</a>`;
    }).join('');
    return container.innerHTML = `<div class="container" style="max-width: 800px; margin: auto; text-align: center">
  <h2 style="font-size: 2rem; margin-bottom: 15px; color: var(--text-main)">
    ${data.title}
  </h2>
  <p style="font-size: 1.05rem; color: var(--text-muted); line-height: 1.6; margin-bottom: 30px;">
    ${data.description}
  </p>
  <div style="display: flex; gap: 12px; justify-content: center; flex-wrap: wrap;">
    ${ctasHtml}
  </div>
</div>`;
  };

  renderCerberus = function(container, data) {
    var pillsHtml;
    pillsHtml = data.pills.map(function(pill) {
      return `<span class=\"cerberus-pill\">${pill}</span>`;
    }).join('');
    return container.innerHTML = `<div class="cerberus-orb"></div>
<div class="container" style="max-width: 860px; margin: auto; text-align: center; position: relative; z-index: 1;">
  <div class="cerberus-badge">
    <span class="cerberus-dot"></span>
    ${data.badge}
  </div>
  <h2 class="cerberus-heading">${data.title}</h2>
  <p class="cerberus-subheading">${data.subheading}</p>
  <p class="cerberus-desc">${data.description}</p>
  <div class="cerberus-pills">
    ${pillsHtml}
  </div>
  <a href="${data.cta.link}" target="_blank" rel="noopener" id="cerberus-cta" class="cerberus-cta">
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
      <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon>
    </svg>
    ${data.cta.text}
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
      <line x1="5" y1="12" x2="19" y2="12"></line>
      <polyline points="12 5 19 12 12 19"></polyline>
    </svg>
  </a>
  <p class="cerberus-footnote">${data.footnote}</p>
</div>`;
  };

  parseCsv = function(text) {
    var char, field, i, inQuotes, j, nextChar, ref, row, rows;
    rows = [];
    row = [];
    field = "";
    inQuotes = false;
    for (i = j = 0, ref = text.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
      char = text[i];
      nextChar = text[i + 1];
      if (inQuotes) {
        if (char === '"' && nextChar === '"') {
          field += '"';
          i += 1;
        } else if (char === '"') {
          inQuotes = false;
        } else {
          field += char;
        }
      } else {
        if (char === '"') {
          inQuotes = true;
        } else if (char === ',') {
          row.push(field);
          field = "";
        } else if (char === '\r') {
          continue;
        } else if (char === '\n') {
          row.push(field);
          rows.push(row);
          row = [];
          field = "";
        } else {
          field += char;
        }
      }
    }
    if (field.length > 0 || row.length > 0) {
      row.push(field);
      rows.push(row);
    }
    return rows.filter(function(r) {
      return !(r.length === 1 && r[0] === "");
    });
  };

  fetchAndRenderCsvTable = async function(url) {
    var btn, cell, col, container, csvText, e, htr, idx, j, k, l, len, len1, len2, ref, ref1, response, row, rows, t, table, tbody, td, th, thead, tr, val;
    container = document.getElementById('csv-table-container');
    if (!container) {
      return;
    }
    container.innerHTML = '<p style="padding: 30px; margin: 0; color: var(--text-main)">Loading table, please wait...</p>';
    try {
      response = (await fetch(url, {
        mode: 'cors'
      }));
      if (!response.ok) {
        throw new Error("Network response was not ok");
      }
      csvText = (await response.text());
      rows = parseCsv(csvText);
      if (rows.length === 0) {
        throw new Error("CSV empty");
      }
      table = document.createElement('table');
      table.className = 'schedule-table';
      
      // Header
      thead = document.createElement('thead');
      htr = document.createElement('tr');
      ref = rows[0];
      for (j = 0, len = ref.length; j < len; j++) {
        t = ref[j];
        th = document.createElement('th');
        th.textContent = t;
        htr.appendChild(th);
      }
      thead.appendChild(htr);
      
      // Body
      tbody = document.createElement('tbody');
      ref1 = rows.slice(1);
      for (k = 0, len1 = ref1.length; k < len1; k++) {
        row = ref1[k];
        tr = document.createElement('tr');
        for (idx = l = 0, len2 = row.length; l < len2; idx = ++l) {
          cell = row[idx];
          td = document.createElement('td');
          col = (rows[0][idx] || "").trim().toLowerCase();
          if (col === "signup form") {
            val = cell.trim();
            btn = document.createElement('a');
            btn.className = "btn btn-primary";
            btn.textContent = "Sign up";
            btn.target = "_blank";
            btn.rel = "noopener";
            btn.href = /^https?:\/\//i.test(val) ? val : "contact.html";
            td.appendChild(btn);
          } else {
            td.textContent = cell;
          }
          tr.appendChild(td);
        }
        tbody.appendChild(tr);
      }
      table.appendChild(thead);
      table.appendChild(tbody);
      container.innerHTML = "";
      return container.appendChild(table);
    } catch (error) {
      e = error;
      return container.innerHTML = '<div style="padding:30px; color:var(--accent);">Unable to load data.</div>';
    }
  };

}).call(this);
