/**
 * SEO & Structured Data (JSON-LD) Module
 * Responsible for generating semantic markup for Google and AI/GPT crawlers.
 * Focuses on 'invisible' SEO to rank for 1000+ keywords without cluttering the UI.
 */

(function () {
  // Comprehensive list of 1000+ highly relevant keywords from Excel
  const SEO_KEYWORDS = [
    "Mentors Noakhali",
    "Mentors Noakhali Branch",
    "Mentors IELTS Noakhali",
    "IELTS Noakhali",
    "Noakhali IELTS",
    "free english assessment",
    "free ielts assessment noakhali",
    "free pte assessment noakhali",
    "ielts pte diagnostic test",
    "english level check noakhali",
    "mentors noakhali free test",
    "free english level test",
    "kids English Noakhali",
    "junior English Noakhali",
    "spoken English Noakhali",
    "English grammar Noakhali",
    "school coaching Noakhali",
    "best coaching centre for IELTS",
    "Cambridge Noakhali Branch",
    "Paramount Zone",
    "Saifur's",
    "Saifur's Chowmuhani Branch",
    "Noakhali College",
    "SA College",
    "NSTU",
    "best Mentors Noakhali",
    "Mentors Noakhali best",
    "top Mentors Noakhali",
    "Mentors Noakhali top",
    "leading Mentors Noakhali",
    "Mentors Noakhali leading",
    "professional Mentors Noakhali",
    "Mentors Noakhali professional",
    "expert Mentors Noakhali",
    "Mentors Noakhali expert",
    "advanced Mentors Noakhali",
    "Mentors Noakhali advanced",
    "beginner Mentors Noakhali",
    "Mentors Noakhali beginner",
    "online Mentors Noakhali",
    "Mentors Noakhali online",
    "offline Mentors Noakhali",
    "Mentors Noakhali offline",
    "near me Mentors Noakhali",
    "Mentors Noakhali near me",
    "admission Mentors Noakhali",
    "Mentors Noakhali admission",
    "course Mentors Noakhali",
    "Mentors Noakhali course",
    "classes Mentors Noakhali",
    "Mentors Noakhali classes",
    "training Mentors Noakhali",
    "Mentors Noakhali training",
    "preparation Mentors Noakhali",
    "Mentors Noakhali preparation",
    "practice Mentors Noakhali",
    "Mentors Noakhali practice",
    "mock test Mentors Noakhali",
    "Mentors Noakhali mock test",
    "band 7 Mentors Noakhali",
    "Mentors Noakhali band 7",
    "band 8 Mentors Noakhali",
    "Mentors Noakhali band 8",
    "band 9 Mentors Noakhali",
    "Mentors Noakhali band 9",
    "affordable Mentors Noakhali",
    "Mentors Noakhali affordable",
    "premium Mentors Noakhali",
    "Mentors Noakhali premium",
    "weekend Mentors Noakhali",
    "Mentors Noakhali weekend",
    "intensive Mentors Noakhali",
    "Mentors Noakhali intensive",
    "2026 Mentors Noakhali",
    "Mentors Noakhali 2026",
    "Bangladesh Mentors Noakhali",
    "Mentors Noakhali Bangladesh",
    "Chowmuhani Mentors Noakhali",
    "Mentors Noakhali Chowmuhani",
    "Maijdee Mentors Noakhali",
    "Mentors Noakhali Maijdee",
    "Sadar Mentors Noakhali",
    "Mentors Noakhali Sadar",
    "student Mentors Noakhali",
    "Mentors Noakhali student",
    "teacher Mentors Noakhali",
    "Mentors Noakhali teacher",
    "academy Mentors Noakhali",
    "Mentors Noakhali academy",
    "learning center Mentors Noakhali",
    "Mentors Noakhali learning center",
    "exam Mentors Noakhali",
    "Mentors Noakhali exam",
    "best Mentors Noakhali Branch",
    "Mentors Noakhali Branch best",
    "top Mentors Noakhali Branch",
    "Mentors Noakhali Branch top",
    "leading Mentors Noakhali Branch",
    "Mentors Noakhali Branch leading",
    "professional Mentors Noakhali Branch",
    "Mentors Noakhali Branch professional",
    "expert Mentors Noakhali Branch",
    "Mentors Noakhali Branch expert",
    "advanced Mentors Noakhali Branch",
    "Mentors Noakhali Branch advanced",
    "beginner Mentors Noakhali Branch",
    "Mentors Noakhali Branch beginner",
    "online Mentors Noakhali Branch",
    "Mentors Noakhali Branch online",
    "offline Mentors Noakhali Branch",
    "Mentors Noakhali Branch offline",
    "near me Mentors Noakhali Branch",
    "Mentors Noakhali Branch near me",
    "admission Mentors Noakhali Branch",
    "Mentors Noakhali Branch admission",
    "course Mentors Noakhali Branch",
    "Mentors Noakhali Branch course",
    "classes Mentors Noakhali Branch",
    "Mentors Noakhali Branch classes",
    "training Mentors Noakhali Branch",
    "Mentors Noakhali Branch training",
    "preparation Mentors Noakhali Branch",
    "Mentors Noakhali Branch preparation",
    "practice Mentors Noakhali Branch",
    "Mentors Noakhali Branch practice",
    "mock test Mentors Noakhali Branch",
    "Mentors Noakhali Branch mock test",
    "band 7 Mentors Noakhali Branch",
    "Mentors Noakhali Branch band 7",
    "band 8 Mentors Noakhali Branch",
    "Mentors Noakhali Branch band 8",
    "band 9 Mentors Noakhali Branch",
    "Mentors Noakhali Branch band 9",
    "affordable Mentors Noakhali Branch",
    "Mentors Noakhali Branch affordable",
    "premium Mentors Noakhali Branch",
    "Mentors Noakhali Branch premium",
    "weekend Mentors Noakhali Branch",
    "Mentors Noakhali Branch weekend",
    "intensive Mentors Noakhali Branch",
    "Mentors Noakhali Branch intensive",
    "2026 Mentors Noakhali Branch",
    "Mentors Noakhali Branch 2026",
    "Bangladesh Mentors Noakhali Branch",
    "Mentors Noakhali Branch Bangladesh",
    "Chowmuhani Mentors Noakhali Branch",
    "Mentors Noakhali Branch Chowmuhani",
    "Maijdee Mentors Noakhali Branch",
    "Mentors Noakhali Branch Maijdee",
    "Sadar Mentors Noakhali Branch",
    "Mentors Noakhali Branch Sadar",
    "student Mentors Noakhali Branch",
    "Mentors Noakhali Branch student",
    "teacher Mentors Noakhali Branch",
    "Mentors Noakhali Branch teacher",
    "academy Mentors Noakhali Branch",
    "Mentors Noakhali Branch academy",
    "learning center Mentors Noakhali Branch",
    "Mentors Noakhali Branch learning center",
    "exam Mentors Noakhali Branch",
    "Mentors Noakhali Branch exam",
    "best Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali best",
    "top Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali top",
    "leading Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali leading",
    "professional Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali professional",
    "expert Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali expert",
    "advanced Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali advanced",
    "beginner Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali beginner",
    "online Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali online",
    "offline Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali offline",
    "near me Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali near me",
    "admission Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali admission",
    "course Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali course",
    "classes Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali classes",
    "training Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali training",
    "preparation Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali preparation",
    "practice Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali practice",
    "mock test Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali mock test",
    "band 7 Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali band 7",
    "band 8 Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali band 8",
    "band 9 Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali band 9",
    "affordable Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali affordable",
    "premium Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali premium",
    "weekend Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali weekend",
    "intensive Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali intensive",
    "2026 Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali 2026",
    "Bangladesh Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali Bangladesh",
    "Chowmuhani Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali Chowmuhani",
    "Maijdee Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali Maijdee",
    "Sadar Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali Sadar",
    "student Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali student",
    "teacher Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali teacher",
    "academy Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali academy",
    "learning center Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali learning center",
    "exam Mentors IELTS Noakhali",
    "Mentors IELTS Noakhali exam",
    "best IELTS Noakhali",
    "IELTS Noakhali best",
    "top IELTS Noakhali",
    "IELTS Noakhali top",
    "leading IELTS Noakhali",
    "IELTS Noakhali leading",
    "professional IELTS Noakhali",
    "IELTS Noakhali professional",
    "expert IELTS Noakhali",
    "IELTS Noakhali expert",
    "advanced IELTS Noakhali",
    "IELTS Noakhali advanced",
    "beginner IELTS Noakhali",
    "IELTS Noakhali beginner",
    "online IELTS Noakhali",
    "IELTS Noakhali online",
    "offline IELTS Noakhali",
    "IELTS Noakhali offline",
    "near me IELTS Noakhali",
    "IELTS Noakhali near me",
    "admission IELTS Noakhali",
    "IELTS Noakhali admission",
    "course IELTS Noakhali",
    "IELTS Noakhali course",
    "classes IELTS Noakhali",
    "IELTS Noakhali classes",
    "training IELTS Noakhali",
    "IELTS Noakhali training",
    "preparation IELTS Noakhali",
    "IELTS Noakhali preparation",
    "practice IELTS Noakhali",
    "IELTS Noakhali practice",
    "mock test IELTS Noakhali",
    "IELTS Noakhali mock test",
    "band 7 IELTS Noakhali",
    "IELTS Noakhali band 7",
    "band 8 IELTS Noakhali",
    "IELTS Noakhali band 8",
    "band 9 IELTS Noakhali",
    "IELTS Noakhali band 9",
    "affordable IELTS Noakhali",
    "IELTS Noakhali affordable",
    "premium IELTS Noakhali",
    "IELTS Noakhali premium",
    "weekend IELTS Noakhali",
    "IELTS Noakhali weekend",
    "intensive IELTS Noakhali",
    "IELTS Noakhali intensive",
    "2026 IELTS Noakhali",
    "IELTS Noakhali 2026",
    "Bangladesh IELTS Noakhali",
    "IELTS Noakhali Bangladesh",
    "Chowmuhani IELTS Noakhali",
    "IELTS Noakhali Chowmuhani",
    "Maijdee IELTS Noakhali",
    "IELTS Noakhali Maijdee",
    "Sadar IELTS Noakhali",
    "IELTS Noakhali Sadar",
    "student IELTS Noakhali",
    "IELTS Noakhali student",
    "teacher IELTS Noakhali",
    "IELTS Noakhali teacher",
    "academy IELTS Noakhali",
    "IELTS Noakhali academy",
    "learning center IELTS Noakhali",
    "IELTS Noakhali learning center",
    "exam IELTS Noakhali",
    "IELTS Noakhali exam",
    "best Noakhali IELTS",
    "Noakhali IELTS best",
    "top Noakhali IELTS",
    "Noakhali IELTS top",
    "leading Noakhali IELTS",
    "Noakhali IELTS leading",
    "professional Noakhali IELTS",
    "Noakhali IELTS professional",
    "expert Noakhali IELTS",
    "Noakhali IELTS expert",
    "advanced Noakhali IELTS",
    "Noakhali IELTS advanced",
    "beginner Noakhali IELTS",
    "Noakhali IELTS beginner",
    "online Noakhali IELTS",
    "Noakhali IELTS online",
    "offline Noakhali IELTS",
    "Noakhali IELTS offline",
    "near me Noakhali IELTS",
    "Noakhali IELTS near me",
    "admission Noakhali IELTS",
    "Noakhali IELTS admission",
    "course Noakhali IELTS",
    "Noakhali IELTS course",
    "classes Noakhali IELTS",
    "Noakhali IELTS classes",
    "training Noakhali IELTS",
    "Noakhali IELTS training",
    "preparation Noakhali IELTS",
    "Noakhali IELTS preparation",
    "practice Noakhali IELTS",
    "Noakhali IELTS practice",
    "mock test Noakhali IELTS",
    "Noakhali IELTS mock test",
    "band 7 Noakhali IELTS",
    "Noakhali IELTS band 7",
    "band 8 Noakhali IELTS",
    "Noakhali IELTS band 8",
    "band 9 Noakhali IELTS",
    "Noakhali IELTS band 9",
    "affordable Noakhali IELTS",
    "Noakhali IELTS affordable",
    "premium Noakhali IELTS",
    "Noakhali IELTS premium",
    "weekend Noakhali IELTS",
    "Noakhali IELTS weekend",
    "intensive Noakhali IELTS",
    "Noakhali IELTS intensive",
    "2026 Noakhali IELTS",
    "Noakhali IELTS 2026",
    "Bangladesh Noakhali IELTS",
    "Noakhali IELTS Bangladesh",
    "Chowmuhani Noakhali IELTS",
    "Noakhali IELTS Chowmuhani",
    "Maijdee Noakhali IELTS",
    "Noakhali IELTS Maijdee",
    "Sadar Noakhali IELTS",
    "Noakhali IELTS Sadar",
    "student Noakhali IELTS",
    "Noakhali IELTS student",
    "teacher Noakhali IELTS",
    "Noakhali IELTS teacher",
    "academy Noakhali IELTS",
    "Noakhali IELTS academy",
    "learning center Noakhali IELTS",
    "Noakhali IELTS learning center",
    "exam Noakhali IELTS",
    "Noakhali IELTS exam",
    "best kids English Noakhali",
    "kids English Noakhali best",
    "top kids English Noakhali",
    "kids English Noakhali top",
    "leading kids English Noakhali",
    "kids English Noakhali leading",
    "professional kids English Noakhali",
    "kids English Noakhali professional",
    "expert kids English Noakhali",
    "kids English Noakhali expert",
    "advanced kids English Noakhali",
    "kids English Noakhali advanced",
    "beginner kids English Noakhali",
    "kids English Noakhali beginner",
    "online kids English Noakhali",
    "kids English Noakhali online",
    "offline kids English Noakhali",
    "kids English Noakhali offline",
    "near me kids English Noakhali",
    "kids English Noakhali near me",
    "admission kids English Noakhali",
    "kids English Noakhali admission",
    "course kids English Noakhali",
    "kids English Noakhali course",
    "classes kids English Noakhali",
    "kids English Noakhali classes",
    "training kids English Noakhali",
    "kids English Noakhali training",
    "preparation kids English Noakhali",
    "kids English Noakhali preparation",
    "practice kids English Noakhali",
    "kids English Noakhali practice",
    "mock test kids English Noakhali",
    "kids English Noakhali mock test",
    "band 7 kids English Noakhali",
    "kids English Noakhali band 7",
    "band 8 kids English Noakhali",
    "kids English Noakhali band 8",
    "band 9 kids English Noakhali",
    "kids English Noakhali band 9",
    "affordable kids English Noakhali",
    "kids English Noakhali affordable",
    "premium kids English Noakhali",
    "kids English Noakhali premium",
    "weekend kids English Noakhali",
    "kids English Noakhali weekend",
    "intensive kids English Noakhali",
    "kids English Noakhali intensive",
    "2026 kids English Noakhali",
    "kids English Noakhali 2026",
    "Bangladesh kids English Noakhali",
    "kids English Noakhali Bangladesh",
    "Chowmuhani kids English Noakhali",
    "kids English Noakhali Chowmuhani",
    "Maijdee kids English Noakhali",
    "kids English Noakhali Maijdee",
    "Sadar kids English Noakhali",
    "kids English Noakhali Sadar",
    "student kids English Noakhali",
    "kids English Noakhali student",
    "teacher kids English Noakhali",
    "kids English Noakhali teacher",
    "academy kids English Noakhali",
    "kids English Noakhali academy",
    "learning center kids English Noakhali",
    "kids English Noakhali learning center",
    "exam kids English Noakhali",
    "kids English Noakhali exam",
    "best junior English Noakhali",
    "junior English Noakhali best",
    "top junior English Noakhali",
    "junior English Noakhali top",
    "leading junior English Noakhali",
    "junior English Noakhali leading",
    "professional junior English Noakhali",
    "junior English Noakhali professional",
    "expert junior English Noakhali",
    "junior English Noakhali expert",
    "advanced junior English Noakhali",
    "junior English Noakhali advanced",
    "beginner junior English Noakhali",
    "junior English Noakhali beginner",
    "online junior English Noakhali",
    "junior English Noakhali online",
    "offline junior English Noakhali",
    "junior English Noakhali offline",
    "near me junior English Noakhali",
    "junior English Noakhali near me",
    "admission junior English Noakhali",
    "junior English Noakhali admission",
    "course junior English Noakhali",
    "junior English Noakhali course",
    "classes junior English Noakhali",
    "junior English Noakhali classes",
    "training junior English Noakhali",
    "junior English Noakhali training",
    "preparation junior English Noakhali",
    "junior English Noakhali preparation",
    "practice junior English Noakhali",
    "junior English Noakhali practice",
    "mock test junior English Noakhali",
    "junior English Noakhali mock test",
    "band 7 junior English Noakhali",
    "junior English Noakhali band 7",
    "band 8 junior English Noakhali",
    "junior English Noakhali band 8",
    "band 9 junior English Noakhali",
    "junior English Noakhali band 9",
    "affordable junior English Noakhali",
    "junior English Noakhali affordable",
    "premium junior English Noakhali",
    "junior English Noakhali premium",
    "weekend junior English Noakhali",
    "junior English Noakhali weekend",
    "intensive junior English Noakhali",
    "junior English Noakhali intensive",
    "2026 junior English Noakhali",
    "junior English Noakhali 2026",
    "Bangladesh junior English Noakhali",
    "junior English Noakhali Bangladesh",
    "Chowmuhani junior English Noakhali",
    "junior English Noakhali Chowmuhani",
    "Maijdee junior English Noakhali",
    "junior English Noakhali Maijdee",
    "Sadar junior English Noakhali",
    "junior English Noakhali Sadar",
    "student junior English Noakhali",
    "junior English Noakhali student",
    "teacher junior English Noakhali",
    "junior English Noakhali teacher",
    "academy junior English Noakhali",
    "junior English Noakhali academy",
    "learning center junior English Noakhali",
    "junior English Noakhali learning center",
    "exam junior English Noakhali",
    "junior English Noakhali exam",
    "best spoken English Noakhali",
    "spoken English Noakhali best",
    "top spoken English Noakhali",
    "spoken English Noakhali top",
    "leading spoken English Noakhali",
    "spoken English Noakhali leading",
    "professional spoken English Noakhali",
    "spoken English Noakhali professional",
    "expert spoken English Noakhali",
    "spoken English Noakhali expert",
    "advanced spoken English Noakhali",
    "spoken English Noakhali advanced",
    "beginner spoken English Noakhali",
    "spoken English Noakhali beginner",
    "online spoken English Noakhali",
    "spoken English Noakhali online",
    "offline spoken English Noakhali",
    "spoken English Noakhali offline",
    "near me spoken English Noakhali",
    "spoken English Noakhali near me",
    "admission spoken English Noakhali",
    "spoken English Noakhali admission",
    "course spoken English Noakhali",
    "spoken English Noakhali course",
    "classes spoken English Noakhali",
    "spoken English Noakhali classes",
    "training spoken English Noakhali",
    "spoken English Noakhali training",
    "preparation spoken English Noakhali",
    "spoken English Noakhali preparation",
    "practice spoken English Noakhali",
    "spoken English Noakhali practice",
    "mock test spoken English Noakhali",
    "spoken English Noakhali mock test",
    "band 7 spoken English Noakhali",
    "spoken English Noakhali band 7",
    "band 8 spoken English Noakhali",
    "spoken English Noakhali band 8",
    "band 9 spoken English Noakhali",
    "spoken English Noakhali band 9",
    "affordable spoken English Noakhali",
    "spoken English Noakhali affordable",
    "premium spoken English Noakhali",
    "spoken English Noakhali premium",
    "weekend spoken English Noakhali",
    "spoken English Noakhali weekend",
    "intensive spoken English Noakhali",
    "spoken English Noakhali intensive",
    "2026 spoken English Noakhali",
    "spoken English Noakhali 2026",
    "Bangladesh spoken English Noakhali",
    "spoken English Noakhali Bangladesh",
    "Chowmuhani spoken English Noakhali",
    "spoken English Noakhali Chowmuhani",
    "Maijdee spoken English Noakhali",
    "spoken English Noakhali Maijdee",
    "Sadar spoken English Noakhali",
    "spoken English Noakhali Sadar",
    "student spoken English Noakhali",
    "spoken English Noakhali student",
    "teacher spoken English Noakhali",
    "spoken English Noakhali teacher",
    "academy spoken English Noakhali",
    "spoken English Noakhali academy",
    "learning center spoken English Noakhali",
    "spoken English Noakhali learning center",
    "exam spoken English Noakhali",
    "spoken English Noakhali exam",
    "best English grammar Noakhali",
    "English grammar Noakhali best",
    "top English grammar Noakhali",
    "English grammar Noakhali top",
    "leading English grammar Noakhali",
    "English grammar Noakhali leading",
    "professional English grammar Noakhali",
    "English grammar Noakhali professional",
    "expert English grammar Noakhali",
    "English grammar Noakhali expert",
    "advanced English grammar Noakhali",
    "English grammar Noakhali advanced",
    "beginner English grammar Noakhali",
    "English grammar Noakhali beginner",
    "online English grammar Noakhali",
    "English grammar Noakhali online",
    "offline English grammar Noakhali",
    "English grammar Noakhali offline",
    "near me English grammar Noakhali",
    "English grammar Noakhali near me",
    "admission English grammar Noakhali",
    "English grammar Noakhali admission",
    "course English grammar Noakhali",
    "English grammar Noakhali course",
    "classes English grammar Noakhali",
    "English grammar Noakhali classes",
    "training English grammar Noakhali",
    "English grammar Noakhali training",
    "preparation English grammar Noakhali",
    "English grammar Noakhali preparation",
    "practice English grammar Noakhali",
    "English grammar Noakhali practice",
    "mock test English grammar Noakhali",
    "English grammar Noakhali mock test",
    "band 7 English grammar Noakhali",
    "English grammar Noakhali band 7",
    "band 8 English grammar Noakhali",
    "English grammar Noakhali band 8",
    "band 9 English grammar Noakhali",
    "English grammar Noakhali band 9",
    "affordable English grammar Noakhali",
    "English grammar Noakhali affordable",
    "premium English grammar Noakhali",
    "English grammar Noakhali premium",
    "weekend English grammar Noakhali",
    "English grammar Noakhali weekend",
    "intensive English grammar Noakhali",
    "English grammar Noakhali intensive",
    "2026 English grammar Noakhali",
    "English grammar Noakhali 2026",
    "Bangladesh English grammar Noakhali",
    "English grammar Noakhali Bangladesh",
    "Chowmuhani English grammar Noakhali",
    "English grammar Noakhali Chowmuhani",
    "Maijdee English grammar Noakhali",
    "English grammar Noakhali Maijdee",
    "Sadar English grammar Noakhali",
    "English grammar Noakhali Sadar",
    "student English grammar Noakhali",
    "English grammar Noakhali student",
    "teacher English grammar Noakhali",
    "English grammar Noakhali teacher",
    "academy English grammar Noakhali",
    "English grammar Noakhali academy",
    "learning center English grammar Noakhali",
    "English grammar Noakhali learning center",
    "exam English grammar Noakhali",
    "English grammar Noakhali exam",
    "best school coaching Noakhali",
    "school coaching Noakhali best",
    "top school coaching Noakhali",
    "school coaching Noakhali top",
    "leading school coaching Noakhali",
    "school coaching Noakhali leading",
    "professional school coaching Noakhali",
    "school coaching Noakhali professional",
    "expert school coaching Noakhali",
    "school coaching Noakhali expert",
    "advanced school coaching Noakhali",
    "school coaching Noakhali advanced",
    "beginner school coaching Noakhali",
    "school coaching Noakhali beginner",
    "online school coaching Noakhali",
    "school coaching Noakhali online",
    "offline school coaching Noakhali",
    "school coaching Noakhali offline",
    "near me school coaching Noakhali",
    "school coaching Noakhali near me",
    "admission school coaching Noakhali",
    "school coaching Noakhali admission",
    "course school coaching Noakhali",
    "school coaching Noakhali course",
    "classes school coaching Noakhali",
    "school coaching Noakhali classes",
    "training school coaching Noakhali",
    "school coaching Noakhali training",
    "preparation school coaching Noakhali",
    "school coaching Noakhali preparation",
    "practice school coaching Noakhali",
    "school coaching Noakhali practice",
    "mock test school coaching Noakhali",
    "school coaching Noakhali mock test",
    "band 7 school coaching Noakhali",
    "school coaching Noakhali band 7",
    "band 8 school coaching Noakhali",
    "school coaching Noakhali band 8",
    "band 9 school coaching Noakhali",
    "school coaching Noakhali band 9",
    "affordable school coaching Noakhali",
    "school coaching Noakhali affordable",
    "premium school coaching Noakhali",
    "school coaching Noakhali premium",
    "weekend school coaching Noakhali",
    "school coaching Noakhali weekend",
    "intensive school coaching Noakhali",
    "school coaching Noakhali intensive",
    "2026 school coaching Noakhali",
    "school coaching Noakhali 2026",
    "Bangladesh school coaching Noakhali",
    "school coaching Noakhali Bangladesh",
    "Chowmuhani school coaching Noakhali",
    "school coaching Noakhali Chowmuhani",
    "Maijdee school coaching Noakhali",
    "school coaching Noakhali Maijdee",
    "Sadar school coaching Noakhali",
    "school coaching Noakhali Sadar",
    "student school coaching Noakhali",
    "school coaching Noakhali student",
    "teacher school coaching Noakhali",
    "school coaching Noakhali teacher",
    "academy school coaching Noakhali",
    "school coaching Noakhali academy",
    "learning center school coaching Noakhali",
    "school coaching Noakhali learning center",
    "exam school coaching Noakhali",
    "school coaching Noakhali exam",
    "best best coaching centre for IELTS",
    "best coaching centre for IELTS best",
    "top best coaching centre for IELTS",
    "best coaching centre for IELTS top",
    "leading best coaching centre for IELTS",
    "best coaching centre for IELTS leading",
    "professional best coaching centre for IELTS",
    "best coaching centre for IELTS professional",
    "expert best coaching centre for IELTS",
    "best coaching centre for IELTS expert",
    "advanced best coaching centre for IELTS",
    "best coaching centre for IELTS advanced",
    "beginner best coaching centre for IELTS",
    "best coaching centre for IELTS beginner",
    "online best coaching centre for IELTS",
    "best coaching centre for IELTS online",
    "offline best coaching centre for IELTS",
    "best coaching centre for IELTS offline",
    "near me best coaching centre for IELTS",
    "best coaching centre for IELTS near me",
    "admission best coaching centre for IELTS",
    "best coaching centre for IELTS admission",
    "course best coaching centre for IELTS",
    "best coaching centre for IELTS course",
    "classes best coaching centre for IELTS",
    "best coaching centre for IELTS classes",
    "training best coaching centre for IELTS",
    "best coaching centre for IELTS training",
    "preparation best coaching centre for IELTS",
    "best coaching centre for IELTS preparation",
    "practice best coaching centre for IELTS",
    "best coaching centre for IELTS practice",
    "mock test best coaching centre for IELTS",
    "best coaching centre for IELTS mock test",
    "band 7 best coaching centre for IELTS",
    "best coaching centre for IELTS band 7",
    "band 8 best coaching centre for IELTS",
    "best coaching centre for IELTS band 8",
    "band 9 best coaching centre for IELTS",
    "best coaching centre for IELTS band 9",
    "affordable best coaching centre for IELTS",
    "best coaching centre for IELTS affordable",
    "premium best coaching centre for IELTS",
    "best coaching centre for IELTS premium",
    "weekend best coaching centre for IELTS",
    "best coaching centre for IELTS weekend",
    "intensive best coaching centre for IELTS",
    "best coaching centre for IELTS intensive",
    "2026 best coaching centre for IELTS",
    "best coaching centre for IELTS 2026",
    "Bangladesh best coaching centre for IELTS",
    "best coaching centre for IELTS Bangladesh",
    "Chowmuhani best coaching centre for IELTS",
    "best coaching centre for IELTS Chowmuhani",
    "Maijdee best coaching centre for IELTS",
    "best coaching centre for IELTS Maijdee",
    "Sadar best coaching centre for IELTS",
    "best coaching centre for IELTS Sadar",
    "student best coaching centre for IELTS",
    "best coaching centre for IELTS student",
    "teacher best coaching centre for IELTS",
    "best coaching centre for IELTS teacher",
    "academy best coaching centre for IELTS",
    "best coaching centre for IELTS academy",
    "learning center best coaching centre for IELTS",
    "best coaching centre for IELTS learning center",
    "exam best coaching centre for IELTS",
    "best coaching centre for IELTS exam",
    "best Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch best",
    "top Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch top",
    "leading Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch leading",
    "professional Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch professional",
    "expert Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch expert",
    "advanced Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch advanced",
    "beginner Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch beginner",
    "online Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch online",
    "offline Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch offline",
    "near me Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch near me",
    "admission Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch admission",
    "course Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch course",
    "classes Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch classes",
    "training Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch training",
    "preparation Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch preparation",
    "practice Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch practice",
    "mock test Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch mock test",
    "band 7 Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch band 7",
    "band 8 Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch band 8",
    "band 9 Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch band 9",
    "affordable Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch affordable",
    "premium Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch premium",
    "weekend Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch weekend",
    "intensive Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch intensive",
    "2026 Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch 2026",
    "Bangladesh Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch Bangladesh",
    "Chowmuhani Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch Chowmuhani",
    "Maijdee Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch Maijdee",
    "Sadar Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch Sadar",
    "student Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch student",
    "teacher Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch teacher",
    "academy Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch academy",
    "learning center Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch learning center",
    "exam Cambridge Noakhali Branch",
    "Cambridge Noakhali Branch exam",
    "best Paramount Zone",
    "Paramount Zone best",
    "top Paramount Zone",
    "Paramount Zone top",
    "leading Paramount Zone",
    "Paramount Zone leading",
    "professional Paramount Zone",
    "Paramount Zone professional",
    "expert Paramount Zone",
    "Paramount Zone expert",
    "advanced Paramount Zone",
    "Paramount Zone advanced",
    "beginner Paramount Zone",
    "Paramount Zone beginner",
    "online Paramount Zone",
    "Paramount Zone online",
    "offline Paramount Zone",
    "Paramount Zone offline",
    "near me Paramount Zone",
    "Paramount Zone near me",
    "admission Paramount Zone",
    "Paramount Zone admission",
    "course Paramount Zone",
    "Paramount Zone course",
    "classes Paramount Zone",
    "Paramount Zone classes",
    "training Paramount Zone",
    "Paramount Zone training",
    "preparation Paramount Zone",
    "Paramount Zone preparation",
    "practice Paramount Zone",
    "Paramount Zone practice",
    "mock test Paramount Zone",
    "Paramount Zone mock test",
    "band 7 Paramount Zone",
    "Paramount Zone band 7",
    "band 8 Paramount Zone",
    "Paramount Zone band 8",
    "band 9 Paramount Zone",
    "Paramount Zone band 9",
    "affordable Paramount Zone",
    "Paramount Zone affordable",
    "premium Paramount Zone",
    "Paramount Zone premium",
    "weekend Paramount Zone",
    "Paramount Zone weekend",
    "intensive Paramount Zone",
    "Paramount Zone intensive",
    "2026 Paramount Zone",
    "Paramount Zone 2026",
    "Bangladesh Paramount Zone",
    "Paramount Zone Bangladesh",
    "Chowmuhani Paramount Zone",
    "Paramount Zone Chowmuhani",
    "Maijdee Paramount Zone",
    "Paramount Zone Maijdee",
    "Sadar Paramount Zone",
    "Paramount Zone Sadar",
    "student Paramount Zone",
    "Paramount Zone student",
    "teacher Paramount Zone",
    "Paramount Zone teacher",
    "academy Paramount Zone",
    "Paramount Zone academy",
    "learning center Paramount Zone",
    "Paramount Zone learning center",
    "exam Paramount Zone",
    "Paramount Zone exam",
    "best Saifur's",
    "Saifur's best",
    "top Saifur's",
    "Saifur's top",
    "leading Saifur's",
    "Saifur's leading",
    "professional Saifur's",
    "Saifur's professional",
    "expert Saifur's",
    "Saifur's expert",
    "advanced Saifur's",
    "Saifur's advanced",
    "beginner Saifur's",
    "Saifur's beginner",
    "online Saifur's",
    "Saifur's online",
    "offline Saifur's",
    "Saifur's offline",
    "near me Saifur's",
    "Saifur's near me",
    "admission Saifur's",
    "Saifur's admission",
    "course Saifur's",
    "Saifur's course",
    "classes Saifur's",
    "Saifur's classes",
    "training Saifur's",
    "Saifur's training",
    "preparation Saifur's",
    "Saifur's preparation",
    "practice Saifur's",
    "Saifur's practice",
    "mock test Saifur's",
    "Saifur's mock test",
    "band 7 Saifur's",
    "Saifur's band 7",
    "band 8 Saifur's",
    "Saifur's band 8",
    "band 9 Saifur's",
    "Saifur's band 9",
    "affordable Saifur's",
    "Saifur's affordable",
    "premium Saifur's",
    "Saifur's premium",
    "weekend Saifur's",
    "Saifur's weekend",
    "intensive Saifur's",
    "Saifur's intensive",
    "2026 Saifur's",
    "Saifur's 2026",
    "Bangladesh Saifur's",
    "Saifur's Bangladesh",
    "Chowmuhani Saifur's",
    "Saifur's Chowmuhani",
    "Maijdee Saifur's",
    "Saifur's Maijdee",
    "Sadar Saifur's",
    "Saifur's Sadar",
    "student Saifur's",
    "Saifur's student",
    "teacher Saifur's",
    "Saifur's teacher",
    "academy Saifur's",
    "Saifur's academy",
    "learning center Saifur's",
    "Saifur's learning center",
    "exam Saifur's",
    "Saifur's exam",
    "best Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch best",
    "top Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch top",
    "leading Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch leading",
    "professional Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch professional",
    "expert Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch expert",
    "advanced Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch advanced",
    "beginner Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch beginner",
    "online Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch online",
    "offline Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch offline",
    "near me Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch near me",
    "admission Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch admission",
    "course Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch course",
    "classes Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch classes",
    "training Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch training",
    "preparation Saifur's Chowmuhani Branch",
    "Saifur's Chowmuhani Branch preparation",
  ];

  /**
   * Generate LocalBusiness Schema
   */
  function getLocalBusinessSchema() {
    return {
      "@context": "https://schema.org",
      "@type": "EducationalOrganization",
      name: "Mentors' Noakhali",
      image: "https://mentors.com.bd/noakhali/Media/logo.png",
      "@id": "https://mentors.com.bd/noakhali/",
      url: "https://mentors.com.bd/noakhali/",
      telephone: "+8801321207488",
      address: {
        "@type": "PostalAddress",
        streetAddress: "Maijdee Court, Sonapur Road",
        addressLocality: "Maijdee",
        addressRegion: "Noakhali",
        postalCode: "3800",
        addressCountry: "BD",
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: 22.8687,
        longitude: 91.1011,
      },
      keywords: SEO_KEYWORDS.join(", "),
      description:
        "Premium IELTS, PTE, and Spoken English coaching centre in Noakhali. Expert study abroad consultancy for UK, USA, Canada, and Australia.",
      openingHoursSpecification: {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: [
          "Saturday",
          "Sunday",
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
        ],
        opens: "09:00",
        closes: "20:00",
      },
    };
  }

  /**
   * Generate Course Schemas
   */
  function getCourseSchemas() {
    const courses = [
      {
        name: "IELTS Course Noakhali",
        description:
          "Best IELTS preparation in Noakhali with expert instructors and unlimited mock tests.",
      },
      {
        name: "PTE Academic Coaching Maijdee",
        description:
          "Result-oriented PTE training for Noakhali students aiming for global universities.",
      },
      {
        name: "Spoken English Noakhali",
        description:
          "Practical English speaking and grammar course in Noakhali for career growth.",
      },
      {
        name: "Free English & IELTS Assessment Test",
        description:
          "Get a free diagnostic level test for English, IELTS, and PTE at Mentors' Noakhali Branch. Instant results and recommendation.",
      },
    ];

    return courses.map((c) => ({
      "@context": "https://schema.org",
      "@type": "Course",
      name: c.name,
      description: c.description,
      provider: {
        "@type": "Organization",
        name: "Mentors' Noakhali",
        sameAs: "https://mentors.com.bd/noakhali/",
      },
    }));
  }

  /**
   * Inject Schemas into Head
   */
  function injectSchema(schema) {
    const script = document.createElement("script");
    script.type = "application/ld+json";
    script.text = JSON.stringify(schema);
    document.head.appendChild(script);
  }

  // Run on DOM completion
  document.addEventListener("DOMContentLoaded", () => {
    injectSchema(getLocalBusinessSchema());
    getCourseSchemas().forEach(injectSchema);
  });
})();
