/* ============================================================
   Study Abroad Data
   ============================================================ */

const STUDY_COUNTRIES = [
    {
        id: "uk",
        name: "United Kingdom",
        flag: "🇬🇧",
        tagline: "Explore elite education, lucrative scholarships, and a vibrant international community.",
        glowColor: "rgba(1, 33, 105, 0.4)",
        borderColor: "#012169",
        universities: [
            { name: "City, University of London", location: "London", link: "https://www.city.ac.uk" },
            { name: "London Metropolitan University", location: "London", link: "https://www.londonmet.ac.uk" },
            { name: "London South Bank University", location: "London", link: "https://www.lsbu.ac.uk" },
            { name: "Middlesex University", location: "London", link: "https://www.mdx.ac.uk" },
            { name: "University of East London (UEL)", location: "London", link: "https://www.uel.ac.uk" },
            { name: "University of Greenwich", location: "London", link: "https://www.gre.ac.uk" },
            { name: "University of Law", location: "London", link: "https://www.law.ac.uk" },
            { name: "University of Westminster", location: "London", link: "https://www.westminster.ac.uk" },
            { name: "Ulster University", location: "London", link: "https://www.ulster.ac.uk" },
            { name: "Kingston University", location: "London", link: "https://www.kingston.ac.uk" },
            { name: "Brunel University", location: "London", link: "https://www.brunel.ac.uk" },
            { name: "University of Roehampton", location: "London", link: "https://www.roehampton.ac.uk" },
            { name: "University of Hull - London", location: "London", link: "https://www.hull.ac.uk" },
            { name: "Birmingham City University", location: "Birmingham", link: "https://www.bcu.ac.uk" },
            { name: "University of the West of England", location: "Bristol", link: "https://www.uwe.ac.uk" },
            { name: "University of Chester", location: "Chester", link: "https://www.chester.ac.uk" },
            { name: "Coventry University", location: "Coventry", link: "https://www.coventry.ac.uk" },
            { name: "Keele University", location: "Staffordshire", link: "https://www.keele.ac.uk" },
            { name: "Lancaster University", location: "Lancaster", link: "https://www.lancaster.ac.uk" },
            { name: "Leeds Beckett University", location: "Leeds", link: "https://www.leedsbeckett.ac.uk" },
            { name: "De Montfort University", location: "Leicester", link: "https://www.dmu.ac.uk" },
            { name: "Liverpool John Moores University", location: "Liverpool", link: "https://www.ljmu.ac.uk" },
            { name: "Manchester Metropolitan University (MMU)", location: "Manchester", link: "https://www.mmu.ac.uk" },
            { name: "Teesside University", location: "Middlesbrough", link: "https://www.tees.ac.uk" },
            { name: "Newcastle University", location: "Newcastle upon Tyne", link: "https://www.ncl.ac.uk" },
            { name: "Northumbria University", location: "Newcastle", link: "https://www.northumbria.ac.uk" },
            { name: "Oxford Brookes University", location: "Oxford", link: "https://www.brookes.ac.uk" },
            { name: "Royal Holloway University", location: "London", link: "https://www.royalholloway.ac.uk" },
            { name: "The University of York", location: "York", link: "https://www.york.ac.uk" },
            { name: "Cardiff Metropolitan University", location: "Cardiff", link: "https://www.cardiffmet.ac.uk" },
            { name: "University of South Wales", location: "Cardiff/Pontypridd", link: "https://www.southwales.ac.uk" },
            { name: "Queen's University Belfast", location: "Belfast", link: "https://www.qub.ac.uk" },
            { name: "Glasgow Caledonian University", location: "Glasgow", link: "https://www.gcu.ac.uk" },
            { name: "University of Bath", location: "Bath", link: "https://www.bath.ac.uk" }
        ]
    },
    {
        id: "usa",
        name: "United States",
        flag: "🇺🇸",
        glowColor: "rgba(60, 59, 110, 0.4)",
        borderColor: "#3C3B6E",
        tagline: "Explore elite education, lucrative scholarships, and a vibrant international community.",
        universities: [
            { name: "Long Island University", location: "New York", link: "https://www.liu.edu" },
            { name: "Queens College (GSSP)", location: "New York", link: "https://www.qc.cuny.edu" },
            { name: "Mercy University", location: "New York", link: "https://www.mercy.edu" },
            { name: "Berkeley College", location: "New York/New Jersey", link: "https://berkeleycollege.edu" },
            { name: "Montclair State University", location: "Montclair, NJ", link: "https://www.montclair.edu" },
            { name: "William Paterson University", location: "Wayne, NJ", link: "https://www.wpunj.edu" },
            { name: "University of Bridgeport", location: "Bridgeport, CT", link: "https://www.bridgeport.edu" },
            { name: "Illinois State University", location: "Normal, IL", link: "https://www.illinoisstate.edu" },
            { name: "Texas State University", location: "San Marcos, TX", link: "https://www.txst.edu" },
            { name: "University of North Texas", location: "Denton, TX", link: "https://www.unt.edu" },
            { name: "Colorado State University", location: "Fort Collins, CO", link: "https://www.colostate.edu" },
            { name: "Youngstown State University", location: "Youngstown, OH", link: "https://ysu.edu" },
            { name: "Ashland University", location: "Ashland, OH", link: "https://www.ashland.edu" },
            { name: "Emporia State University", location: "Emporia, KS", link: "https://www.emporia.edu" },
            { name: "Wichita State University", location: "Wichita, KS", link: "https://www.wichita.edu" },
            { name: "Pittsburg State University", location: "Pittsburg, KS", link: "https://www.pittstate.edu" },
            { name: "Oregon State University", location: "Corvallis, OR", link: "https://www.oregonstate.edu" },
            { name: "Florida Atlantic University", location: "Boca Raton, FL", link: "https://www.fau.edu" },
            { name: "The University of Oklahoma", location: "Norman, OK", link: "https://www.ou.edu" },
            { name: "Saint Louis University", location: "St. Louis, MO", link: "https://www.slu.edu" },
            { name: "Webster University", location: "St. Louis, MO", link: "https://www.webster.edu" },
            { name: "Murray State University", location: "Murray, KY", link: "https://www.murraystate.edu" },
            { name: "Midway University", location: "Midway, KY", link: "https://www.midway.edu" },
            { name: "University of Arizona", location: "Tucson, AZ", link: "https://www.arizona.edu" },
            { name: "University of South Alabama", location: "Mobile, AL", link: "https://www.southalabama.edu" },
            { name: "University of Alabama at Birmingham", location: "Birmingham, AL", link: "https://www.uab.edu" },
            { name: "Thomas Jefferson University", location: "Philadelphia, PA", link: "https://www.jefferson.edu" },
            { name: "University of Northern Iowa", location: "Cedar Falls, IA", link: "https://www.uni.edu" },
            { name: "San Francisco State University", location: "San Francisco, CA", link: "https://www.sfsu.edu" },
            { name: "California State University", location: "California", link: "https://www.calstate.edu" }
        ]
    },
    {
        id: "canada",
        name: "Canada",
        flag: "🇨🇦",
        glowColor: "rgba(255, 0, 0, 0.3)",
        borderColor: "#FF0000",
        tagline: "Explore elite education, lucrative scholarships, and a vibrant international community.",
        universities: [
            { name: "University of Manitoba", location: "Winnipeg, MB", link: "https://umanitoba.ca" },
            { name: "International College of Manitoba (ICM)", location: "Winnipeg, MB", link: "https://www.icmcanada.ca" },
            { name: "Toronto Metropolitan University", location: "Toronto, ON", link: "https://www.tmu.ca" },
            { name: "University of Windsor", location: "Windsor, ON", link: "https://www.uwindsor.ca" },
            { name: "Algoma University", location: "Sault Ste. Marie, ON", link: "https://www.algomau.ca" },
            { name: "Laurentian University", location: "Sudbury, ON", link: "https://laurentian.ca" },
            { name: "Lakehead University", location: "Thunder Bay, ON", link: "https://www.lakeheadu.ca" },
            { name: "Trent University", location: "Peterborough, ON", link: "https://www.trentu.ca" },
            { name: "University of Guelph", location: "Guelph, ON", link: "https://www.uoguelph.ca" },
            { name: "Seneca College", location: "Toronto, ON", link: "https://www.senecacollege.ca" },
            { name: "Centennial College", location: "Toronto, ON", link: "https://www.centennialcollege.ca" },
            { name: "Ontario Tech University", location: "Oshawa, ON", link: "https://ontariotechu.ca" },
            { name: "University of Niagara Falls", location: "Niagara Falls, ON", link: "https://www.niagara.edu" },
            { name: "International Business University", location: "Toronto, ON", link: "https://www.ibu.edu" },
            { name: "Carleton University", location: "Ottawa, ON", link: "https://carleton.ca" },
            { name: "University of Saskatchewan", location: "Saskatoon, SK", link: "https://www.usask.ca" },
            { name: "University of Regina", location: "Regina, SK", link: "https://www.uregina.ca" },
            { name: "Fraser International College (FIC)", location: "Burnaby, BC", link: "https://www.fic.ubc.ca" },
            { name: "NYIT - Vancouver", location: "Vancouver, BC", link: "https://www.nyit.edu/vancouver" },
            { name: "University of Victoria", location: "Victoria, BC", link: "https://www.uvic.ca" },
            { name: "University Canada West", location: "Vancouver, BC", link: "https://ucanwest.ca" },
            { name: "Fairleigh Dickinson University", location: "Vancouver, BC", link: "https://www.fdu.edu" },
            { name: "University of Fraser Valley", location: "Abbotsford, BC", link: "https://www.ufv.ca" },
            { name: "Concordia University of Edmonton", location: "Edmonton, AB", link: "https://www.cue.edu" },
            { name: "University of Alberta", location: "Edmonton, AB", link: "https://www.ualberta.ca" },
            { name: "Dalhousie University", location: "Halifax, NS", link: "https://www.dal.ca" },
            { name: "Cape Breton University", location: "Sydney, NS", link: "https://www.cbu.ca" },
            { name: "University of New Brunswick - UNB", location: "New Brunswick", link: "https://www.unb.ca" },
            { name: "Memorial University of Newfoundland", location: "St. John's, NL", link: "https://www.mun.ca" }
        ]
    },
    {
        id: "australia",
        name: "Australia",
        flag: "🇦🇺",
        glowColor: "rgba(0, 0, 139, 0.4)",
        borderColor: "#00008B",
        tagline: "Explore elite education, lucrative scholarships, and a vibrant international community.",
        universities: [
            { name: "Macquarie University", location: "Sydney, NSW", link: "https://www.mq.edu.au" },
            { name: "Deakin University", location: "Melbourne, VIC", link: "https://www.deakin.edu.au" },
            { name: "La Trobe University", location: "Melbourne, VIC", link: "https://www.latrobe.edu.au" },
            { name: "Victoria University", location: "Melbourne, VIC", link: "https://www.vu.edu.au" },
            { name: "Curtin University", location: "Perth, WA", link: "https://www.curtin.edu.au" },
            { name: "University of Tasmania", location: "Hobart, TAS", link: "https://www.utas.edu.au" },
            { name: "University of New England", location: "Armidale, NSW", link: "https://www.une.edu.au" },
            { name: "Australian Catholic University", location: "Melbourne, VIC", link: "https://www.acu.edu.au" },
            { name: "University of Western Australia", location: "Perth, WA", link: "https://www.uwa.edu.au" },
            { name: "Southern Cross University", location: "Brisbane, QLD", link: "https://www.scu.edu.au" },
            { name: "James Cook University", location: "Townsville, QLD", link: "https://www.jcu.edu.au" },
            { name: "Charles Darwin University", location: "Darwin, NT", link: "https://www.cdu.edu.au" },
            { name: "NAVITAS", location: "Multiple", link: "https://www.navitas.com" },
            { name: "Charles Sturt University Sydney", location: "Sydney, NSW", link: "https://www.csu.edu.au" },
            { name: "Western Sydney University Sydney City Campus", location: "Sydney, NSW", link: "https://www.westernsydney.edu.au" },
            { name: "La Trobe University Sydney Campus", location: "Sydney, NSW", link: "https://www.latrobe.edu.au" },
            { name: "Edith Cowan College", location: "Perth, WA", link: "https://www.ecu.edu.au" },
            { name: "Eynesbury College", location: "Adelaide, SA", link: "https://www.eynesbury.sa.edu.au" },
            { name: "Griffith College", location: "Brisbane, QLD", link: "https://www.griffith.ie" },
            { name: "SAIBT", location: "Adelaide, SA", link: "https://saibt.sa.edu.au" },
            { name: "SIBT", location: "Sydney, NSW", link: "https://www.sibt.nsw.edu.au" },
            { name: "University of Canberra College", location: "Canberra, ACT", link: "https://www.canberra.edu.au" },
            { name: "La Trobe College", location: "Melbourne, VIC", link: "https://www.latrobe.edu.au" },
            { name: "ECA", location: "Multiple", link: "https://www.eca.edu.au" },
            { name: "Victoria University Sydney", location: "Sydney, NSW", link: "https://www.vu.edu.au" },
            { name: "University of Canberra Sydney", location: "Sydney, NSW", link: "https://www.canberra.edu.au" },
            { name: "Swinburne University of Technology Sydney", location: "Sydney, NSW", link: "https://www.swinburne.edu.au" },
            { name: "Victoria University Brisbane", location: "Brisbane, QLD", link: "https://www.vu.edu.au" },
            { name: "University of Sunshine Coast", location: "Sunshine Coast, QLD", link: "https://www.usc.edu.au" },
            { name: "UP Education", location: "Multiple", link: "https://up.education" },
            { name: "CDU International College", location: "Darwin, NT", link: "https://www.cdu.edu.au" },
            { name: "UTAS International Pathway College", location: "Hobart, TAS", link: "https://www.utas.edu.au" },
            { name: "Swinburne University of Technology College", location: "Melbourne, VIC", link: "https://www.swinburne.edu.au" },
            { name: "International College of Hotel Management (ICHM)", location: "Adelaide, SA", link: "https://www.ichm.edu.au" }
        ]
    },
    {
        id: "newzealand",
        name: "New Zealand",
        flag: "🇳🇿",
        glowColor: "rgba(0, 36, 125, 0.4)",
        borderColor: "#00247D",
        tagline: "Quality education in a safe, welcoming, and naturally beautiful environment.",
        universities: [
            { name: "Auckland University of Technology", location: "Auckland", link: "https://www.aut.ac.nz" },
            { name: "University of Auckland", location: "Auckland", link: "https://www.auckland.ac.nz" },
            { name: "University of Canterbury", location: "Christchurch", link: "https://www.canterbury.ac.nz" },
            { name: "University of Otago", location: "Dunedin", link: "https://www.otago.ac.nz" },
            { name: "Lincoln University", location: "Lincoln", link: "https://www.lincoln.ac.nz" },
            { name: "University of Waikato", location: "Hamilton", link: "https://www.waikato.ac.nz" },
            { name: "Massey University", location: "Palmerston North", link: "https://www.massey.ac.nz" },
            { name: "Victoria University of Wellington", location: "Wellington", link: "https://www.wgtn.ac.nz" }
        ]
    },
    {
        id: "ireland",
        name: "Ireland",
        flag: "🇮🇪",
        glowColor: "rgba(22, 155, 98, 0.4)",
        borderColor: "#169B62",
        tagline: "European hub for technology and innovation with a rich cultural heritage.",
        universities: [
            { name: "University of Limerick", location: "Limerick", link: "https://www.ul.ie" },
            { name: "Maynooth University", location: "Maynooth", link: "https://www.maynoothuniversity.ie" },
            { name: "Unihaven College", location: "Ireland", link: "https://www.oncampus.global/europe/campuses/oncampus-ireland/unihaven-college/about-unihaven-college.htm" },
            { name: "University of Galway, Ireland", location: "Galway", link: "https://www.universityofgalway.ie" },
            { name: "Trinity College Dublin", location: "Dublin", link: "https://www.tcd.ie" },
            { name: "Dublin City University", location: "Dublin", link: "https://www.dcu.ie" },
            { name: "Griffith College", location: "Dublin", link: "https://www.griffith.ie" },
            { name: "Independent College", location: "Dublin", link: "https://www.independentcolleges.ie" }
        ]
    },
    {
        id: "malaysia",
        name: "Malaysia",
        flag: "🇲🇾",
        glowColor: "rgba(255, 204, 0, 0.5)",
        borderColor: "#FFCC00",
        tagline: "Affordable, high-quality education in the heart of Southeast Asia.",
        universities: [
            { name: "Taylor's University", location: "Subang Jaya", link: "https://www.taylors.edu.my" },
            { name: "University of Wollongong Malaysia", location: "Shah Alam", link: "https://www.uow.edu.au/malaysia" },
            { name: "Curtin University Malaysia", location: "Miri, Sarawak", link: "https://www.curtin.edu.my" },
            { name: "Newcastle University Medicine Malaysia", location: "Johor", link: "https://newcastle.edu.my" },
            { name: "International Medical University (IMU)", location: "Kuala Lumpur", link: "https://www.imu.edu.my" },
            { name: "Sunway University", location: "Subang Jaya", link: "https://www.sunway.edu.my" },
            { name: "UCSI University", location: "Kuala Lumpur", link: "https://www.ucsiuniversity.edu.my" },
            { name: "University of Cyberjaya", location: "Cyberjaya", link: "https://www.ucyberjaya.edu.my" },
            { name: "Asia Pacific University of Technology & Innovation (APU)", location: "Kuala Lumpur", link: "https://www.apu.edu.my" },
            { name: "Universiti Teknologi Malaysia (UTM)", location: "Skudai, Johor", link: "https://www.utm.my" },
            { name: "INTI International University", location: "Nilai", link: "https://www.inti.edu.my" },
            { name: "Heriot-Watt University Malaysia", location: "Putrajaya", link: "https://www.hw.ac.uk/uk/malaysia" },
            { name: "Swinburne University of Technology Malaysia", location: "Kuching, Sarawak", link: "https://www.swinburne.edu.my" },
            { name: "Brickfields Asia College", location: "Kuala Lumpur", link: "https://www.bac.edu.my" }
        ]
    },
    {
        id: "sweden",
        name: "Sweden",
        flag: "🇸🇪",
        glowColor: "rgba(0, 106, 167, 0.4)",
        borderColor: "#006AA7",
        tagline: "Affordable tuition & high-quality EU education.",
        universities: []
    },
    {
        id: "denmark",
        name: "Denmark",
        flag: "🇩🇰",
        glowColor: "rgba(198, 12, 48, 0.3)",
        borderColor: "#C60C30",
        tagline: "Long study gaps accepted + EU travel access.",
        universities: []
    },
    {
        id: "bangladesh",
        name: "Bangladesh",
        flag: "🇧🇩",
        glowColor: "rgba(0, 106, 78, 0.4)",
        borderColor: "#006A4E",
        tagline: "International-standard pathway programs.",
        universities: [
            { name: "Asian University for Women", location: "Chittagong", link: "https://www.asian-university.org" },
            { name: "Universal College Bangladesh", location: "Dhaka", link: "https://www.ucb.edu.bd" },
            { name: "NCUK", location: "Dhaka", link: "https://www.ncuk.ac.uk" },
            { name: "UTS College Bangladesh", location: "Dhaka", link: "https://www.utsc.edu.bd" }
        ]
    }
];
