// Generated by CoffeeScript 2.7.0
(function() {
  /*
    Team Data
  */
  window.TEAM = [
    {
      name: "MD Eachin",
      avatar: "Media/All employees photo/Md-Eachin.png",
      badge: "Branch Director",
      bio: "Oversees operations and strategic direction of the Noakhali branch, bringing years of institutional leadership to build a world-class learning environment.",
      social: {
        facebook: "https://www.facebook.com/share/18WzVPhoQX/",
        whatsapp: "8801746735616",
        imo: "8801746735616",
        viber: "8801746735616",
        phone: "8801746735616"
      }
    },
    {
      name: "Kamrul Islam Rasel",
      avatar: "Media/All employees photo/Kamrul-Islam-Rasel.png",
      badge: "Branch Chief Executive Officer",
      featured: true,
      bio: "Drives the vision and mission of Mentors' Noakhali, ensuring every student receives an exceptional learning experience aligned with the national standard of excellence.",
      social: {
        facebook: "https://www.facebook.com/share/14byiNFyiRq/",
        whatsapp: "4571486905",
        imo: "4571486905",
        viber: "4571486905",
        phone: "4571486905"
      }
    },
    {
      name: "Linkon John Mendez",
      avatar: "Media/All employees photo/Linkon-John-Mendez.png",
      badge: "Branch Manager",
      bio: "Manages day-to-day branch activities, coordinates instructors and schedules, and ensures every student feels supported throughout their journey at the branch.",
      social: {
        facebook: "https://www.facebook.com/share/1Gk3KDa7oP/",
        whatsapp: "8801625414199",
        imo: "8801625414199",
        viber: "8801625414199",
        phone: "8801625414199"
      }
    },
    {
      name: "MD Arman",
      avatar: "Media/All employees photo/Md-Arman.png",
      badge: "Office Assistant",
      bio: "Supports the branch's daily administrative functions, helping students and staff with smooth operations and a welcoming branch experience.",
      social: {
        facebook: "https://www.facebook.com/share/1HBp7owA2o/",
        whatsapp: "8801581568219",
        imo: "8801581568219",
        viber: "8801581568219",
        phone: "8801581568219"
      }
    },
    {
      name: "Hanif Hridoy",
      avatar: "Media/All employees photo/Md-Hanif-Hridoy.png",
      badge: "Head of Multimedia",
      bio: "Leads all multimedia and content creation efforts, producing visual assets and digital content that showcase the branch's programmes and achievements.",
      social: {
        facebook: "https://www.facebook.com/share/17ofrmNpT3/",
        whatsapp: "8801302002268",
        imo: "8801302002268",
        viber: "8801302002268",
        phone: "8801302002268"
      }
    },
    {
      name: "Omar Hosen",
      avatar: "Media/All employees photo/Omar-Hosen-rahad.png",
      badge: "Senior Marketing Officer",
      bio: "Drives the branch's outreach and marketing initiatives, growing awareness in the community and attracting students to Mentors' programmes.",
      social: {
        facebook: "https://www.facebook.com/share/1Ep5cDEd5s/",
        whatsapp: "8801625245887",
        imo: "8801625245887",
        viber: "8801625245887",
        phone: "8801625245887"
      }
    },
    {
      name: "Nusrat Ahammad Sayma",
      avatar: "Media/All employees photo/Nusrat-Ahammad-Sayma.png",
      badge: "Call Centre Executive",
      theme: "pink",
      social: {
        facebook: "https://www.facebook.com/nusrat.ahammad.sayma",
        whatsapp: "8801766995310",
        imo: "8801766995310",
        viber: "8801766995310",
        phone: "8801766995310"
      }
    },
    {
      name: "Subah Tasnia",
      avatar: "Media/All employees photo/Subah-Tasnia.png",
      badge: "Kids' Instructor",
      theme: "pink",
      social: {
        facebook: "https://www.facebook.com/share/1DvNp79yQG/",
        whatsapp: "8801815639433",
        imo: "8801815639433",
        viber: "8801815639433",
        phone: "8801815639433"
      }
    },
    {
      name: "Iffat Jarin Nabila",
      avatar: "Media/All employees photo/Iffat-Jarin-Nabila.png",
      badge: "Senior Executive Officer",
      theme: "pink",
      social: {
        facebook: "https://www.facebook.com/share/18YJtvbKWq/",
        whatsapp: "8801749845350",
        imo: "8801749845350",
        viber: "8801749845350",
        phone: "8801749845350"
      }
    }
  ];

}).call(this);
