// Generated by CoffeeScript 2.7.0
(function() {
  /*
    Team Renderer
  */
  var SOCIAL_ICONS, renderTeam;

  SOCIAL_ICONS = {
    facebook: `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>`,
    whatsapp: `<svg width="16" height="16" viewBox="0 0 24 24" fill="white"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 0 1 2.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 0 0-3.48-8.413Z"/></svg>`,
    imo: `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2z"></path><path d="M8 9h8M8 13h5"></path></svg>`,
    viber: `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3h.01a9 9 0 0 1 9.78 9.79z"></path><path d="M16 13.5a3 3 0 0 1-1.5 1.5l-1 .4a1 1 0 0 1-1.1-.3l-1.2-1.5a1 1 0 0 1 .1-1.4l.8-.6a1 1 0 0 0 .3-1.1l-.3-1a3 3 0 0 1 1.5-1.5 3 3 0 0 1 2.1 0 3 3 0 0 1 1.1 2.1 3 3 0 0 1-1 2.2z"></path></svg>`,
    phone: `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>`
  };

  document.addEventListener('DOMContentLoaded', function() {
    var grid;
    grid = document.querySelector('.team-grid');
    if (grid) {
      return renderTeam(grid);
    }
  });

  renderTeam = function(container) {
    if (!(container && window.TEAM)) {
      return;
    }
    return container.innerHTML = window.TEAM.map(function(member) {
      var bioHtml, featuredBadge, featuredClass, pinkThemeClass, socialHtml, socialLinks;
      socialLinks = member.social || {};
      socialHtml = Object.entries(socialLinks).map(function([platform, value]) {
        var href, targetAttr;
        if (!value) {
          return "";
        }
        href = (function() {
          switch (platform) {
            case "whatsapp":
              return `https://wa.me/${value}`;
            case "imo":
              return `https://imo.im/${value}`;
            case "viber":
              return `viber://chat?number=%2B${value}`;
            case "phone":
              return `tel:+${value}`;
            default:
              return value;
          }
        })();
        targetAttr = platform !== "phone" ? 'target="_blank" rel="noopener"' : "";
        return `<a class="${platform}" href="${href}" ${targetAttr} aria-label="${platform}">
  ${SOCIAL_ICONS[platform] || ""}
</a>`;
      }).join('');
      featuredClass = member.featured ? "featured-card" : "";
      pinkThemeClass = member.theme === "pink" ? "pink-theme" : "";
      featuredBadge = member.featured ? "featured-badge" : "";
      bioHtml = member.bio ? `<p class=\"team-bio\">${member.bio}</p>` : "";
      return `<div class="team-card ${featuredClass} ${pinkThemeClass}">
  <div class="team-avatar">
    <img src="${member.avatar}" alt="${member.name}" />
  </div>
  <div class="team-badge ${featuredBadge}">${member.badge}</div>
  <h3 class="team-name">${member.name}</h3>
  ${bioHtml}
  <div class="team-social">
    <div class="team-social">
      ${socialHtml}
    </div>
  </div>
</div>`;
    }).join('');
  };

}).call(this);
